---

- name:       Install packages
  sudo:       yes
  apt:        pkg={{ item }} state=installed
  with_items:
    - lib32gcc1

- name:       Download SteamCMD
  get_url:
     url:  http://media.steampowered.com/installer/steamcmd_linux.tar.gz
     dest: "{{ install_dir }}/steamcmd_linux.tar.gz"

- file:
    path:  "{{ install_dir }}/steamcmd"
    state: directory

- unarchive:
     src:  "{{ install_dir }}/steamcmd_linux.tar.gz"
     dest: "{{ install_dir }}/steamcmd/"
     copy: no

- template:
    src:  update-cs-go.j2
    dest: "{{ install_dir }}/steamcmd/update-cs-go"

- command: ./steamcmd.sh +runscript {{ install_dir }}/steamcmd/update-cs-go
  args:
     chdir: "{{ install_dir }}/steamcmd/"
